### ISSUE TITLE
[FEAT]: 상세페이지 api 연동

### ISSUE THREAD

**Issue by Oh-Donghan** [Oh-Donghan/front-end#36]
## 📌 이슈 내용
> 상세페이지에서 필요한 데이터를 서버로부터 가져오는 API를 연동

<br>

## 📝 To-do
- [x] API 엔드포인트 설정 및 호출
- [x] 데이터 로딩 중 상태 처리
- [x] API 연동 후 데이터가 정상적으로 화면에 표시되는지 확인
- [x] 오류 발생 시 사용자에게 적절한 피드백 제공
